In [3]:
import numpy as np
import numpy.ma as ma
import pandas as pd

#### 1. How likely is it that you roll doubles when rolling two dice?

ANSWER: 0.1658

In [4]:
# number of simulations
n_simulations = nrows = 100_000
# number of dice/columns in array
n_dice = ncols = 2
# define array with 10,000 instances of a randome choice of two die rolls
rolls = np.random.choice([1, 2, 3, 4, 5, 6], n_simulations * n_dice).reshape(nrows, ncols)

In [5]:
# method 1: Use pd DataFrame to compare columns
rolls_df = pd.DataFrame(rolls)
(rolls_df[0] == rolls_df [1]).sum() / len(rolls_df)

0.1658

In [6]:
# method 2 use slices to compare columns
rolls[:,0]
rolls[:,1]
(rolls[:,0] == rolls[:,1]).mean()

0.1658

#### 2. If you flip 8 coins, what is the probability of getting exactly 3 heads? 
ANSWER: 0.21805
#### What is the probability of getting more than 3 heads?
ANSWER: 0.63741

In [7]:
# define outcomes
outcomes = ['H','T']
# number of trial/columns
n_trials = 8
# number of simulations
n_simulations = 100_000

In [8]:
# Create a matrix of random numbers
eight_flips = np.random.choice(outcomes, (n_simulations, n_trials))

In [9]:
# Apply the sum aggregate to the rows to find the results of each simulation
(eight_flips == 'H').sum(axis=1)

array([2, 4, 5, ..., 3, 4, 3])

In [10]:
# Use these results to create a bool mask to apply to our array
((eight_flips == 'H').sum(axis=1) == 3)

array([False, False, False, ...,  True, False,  True])

In [11]:
# to find our experimental probability count the number of successes and divide by the number of simulations
((eight_flips == 'H').sum(axis=1) == 3).sum() / n_simulations

0.21805

In [12]:
# Find the probability of getting more than three heads
((eight_flips == 'H').sum(axis=1) > 3).sum() / n_simulations

0.63741

#### 3. There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

ANSWER: 0.06166

In [13]:
# DEFINE OUTCOMES
outcomes = ['WD', 'WD', 'WD', 'DS']
# number of billboards/trials/columns
n_trials = 2
# number of simulations
n_simulations = 100_000

In [14]:
# Create a matrix of random numbers
billboards = np.random.choice(outcomes, (n_simulations, n_trials))
# Create a dataframe from the array so we can use pandas
billboards_df = pd.DataFrame(billboards)

In [15]:
# Create a bool mask of successful outcomes
ds_mask = (billboards_df[0] == 'DS') & (billboards_df[1] == 'DS')
# divide the length of the successful outcomes by the number of simulations
len(billboards[ds_mask]) / len(billboards)

0.06166

#### 4. Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5 a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon? (Remember, if you have mean and standard deviation, use the np.random.normal) You'll need to make a judgement call on how to handle some of your values

ANSWER: 0.61616

In [16]:
avg = 3
std = 1.5
# There are 5 full days before EOD Friday, so our trial number is 5. Lets run 10,000 simulations.
n_simulations = 100_000
n_trials = 5
# Create array for normal distributions and random values with a mean of 3 and stdv of 1.5
poptarts = np.random.normal(avg, std, (n_simulations, n_trials))
poptarts

array([[1.51495258, 3.90474107, 3.06207462, 4.05344693, 4.22386959],
       [0.99459346, 2.04627035, 3.15213162, 2.73235026, 2.56572471],
       [6.11751126, 4.51660877, 1.588424  , 1.07958876, 2.53143228],
       ...,
       [5.23781324, 2.04610673, 4.32124306, 1.00775978, 6.6649465 ],
       [3.45536713, 1.69105728, 4.02580464, 3.792423  , 1.78772204],
       [2.94865281, 5.24111802, 1.53098588, 0.87887611, 2.73097909]])

In [17]:
# A successful simulation is one in which 16 or fewer poptarts have been purchased before me.
# Find the sum of successful simulations and divide by the total number of simulations.
(poptarts.sum(axis=1) <= 16).sum() / n_simulations

0.61616

#### 5. Compare Heights:
    - Men have an average height of 178 cm and standard deviation of 8cm.
    - Women have a mean of 170, sd = 6cm.
##### If a man and woman are chosen at random, what is the likelihood the woman is taller than the man?
ANSWER: 0.211791

In [18]:
# Establish variables for male and female average height and stdv
male_avg = 178
male_std = 8
female_avg = 170
female_std = 6
n_trials = 1_000_000
# Create arrays of 10,000 simulations for males and females
male_array = np.random.normal(male_avg, male_std, n_trials)
female_array = np.random.normal(female_avg, female_std, n_trials)
# Subtract male_array values from female_array values 
height_diff = female_array - male_array
# Create bool mask for differences greater than zero.
height_diff > 0
# Sum successful trials and divide by total number of trials
(height_diff > 0).sum() / n_trials

0.212167

#### 6. When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. 
What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?

What is the probability that we observe an installation issue within the first 150 students that download anaconda?

How likely is it that 450 students all download anaconda without an issue?

In [29]:
# Probability of corruption:
p_corrupt = 1/250
# 10,000 simulations:
n_simulations = n_rows = 100_000

In [40]:
# Odds of no corruption after 50 downloads:
n_trials = ncols = 50
# Create matrix
corrupt = np.random.random((nrows, ncols))
# Bool mask for values less than our probability
corrupted = corrupt < p_corrupt
# Find the sum of successful simulations and average
(corrupted.sum(axis=1) == 0).mean()

0.8198

In [41]:
# Odds of no corruption after 100 students:
n_trials = ncols = 100
# Create matrix
corrupt = np.random.random((nrows, ncols))
# Bool mask for values less than our probability
corrupted = corrupt < p_corrupt
# Find the sum of successful simulations and average
(corrupted.sum(axis=1) == 0).mean()

0.6584

In [47]:
# Probability of corruption within the first 150 downloads:
n_trials = ncols = 150
# Create matrix
corrupt = np.random.random((nrows, ncols))
# Bool mask for values less than our probability
((corrupt < p_corrupt).sum(axis=1) > 0).mean()

0.45415

In [49]:
# How likely is it that after 450 downloads there were no issues:
n_trials = ncols = 450
# Create matrix
corrupt = np.random.random((nrows, ncols))
# Bool mask for values less than our probability
((corrupt < p_corrupt).sum(axis=1) == 0).mean()

0.16426

#### 7. There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?

How likely is it that a food truck will show up sometime this week?

In [71]:
outcomes = ['truck', 'no_truck']
p_truck = .7
n_simulations = 100_000
n_trials = 3
# trials are 3 days
truck_sim = np.random.choice(outcomes, size=(n_simulations, n_trials), p=(p_truck, 0.3))
((truck_sim == 'truck').sum(axis=1) == 0).mean()

0.02611

In [72]:
# How likely is it that a food truck will show up sometime this week?
# Change number of trials to 7 
n_trials = 7
# Create matrix
truck_sim = np.random.choice(outcomes, size=(n_simulations, n_trials), p=(p_truck, 0.3))
((truck_sim == 'truck').sum(axis=1) > 0).mean()

0.99983

#### 8. If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?



In [80]:
n_trials = ncols = 23
n_simulations = nrows = 100_000

# Create matrix
birthday = np.random.choice(range(365),size=(n_simulations, n_trials))
birthday

array([[ 31,  66, 169, ...,  19,  81, 363],
       [180,  91, 172, ...,  97, 109, 117],
       [ 41, 215, 345, ..., 315,  59, 141],
       ...,
       [318, 242, 228, ..., 155, 233, 313],
       [207, 303,  60, ..., 197, 166, 160],
       [199, 162, 167, ...,  42, 295,   1]])

In [83]:
birthday_df = pd.DataFrame(birthday)
(birthday_df.nunique(axis=1) < n_trials).mean()

0.50705

In [84]:
# For 20 people:
n_trials = ncols = 20

# Create matrix
birthday = np.random.choice(range(365),size=(n_simulations, n_trials))
birthday_df = pd.DataFrame(birthday)
(birthday_df.nunique(axis=1) < n_trials).mean()

0.41076

In [85]:
# For 40 people:
n_trials = ncols = 40

# Create matrix
birthday = np.random.choice(range(365),size=(n_simulations, n_trials))
birthday_df = pd.DataFrame(birthday)
(birthday_df.nunique(axis=1) < n_trials).mean()

0.89052